# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Disciplinas (UFBA)
email: rodrigo@dcc.ufba.br
description: > # this means to ignore newlines until "baseurl:"
  Material de disciplinas.
baseurl: "/aulas" # the subpath of your site, e.g. /blog
url: "https://rodrigorgs.github.io/" # the base hostname & protocol for your site
twitter_username: xrodrigorgs
github_username:  rodrigorgs

# Build settings
markdown: kramdown
theme: minima


# Reveal.js

reveal_path: lib/reveal.js/
reveal_theme_path: lib/reveal.js/css/theme/ 
reveal_theme: white.css
reveal_transition: default
# Embed Server-side speaker notes?
reveal_notes_server: false
reveal_options: 
reveal_dependencies: 